parameters:
    bitbag.dhl_wsdl: https://dhl24.com.pl

services:
    bitbag.dhl_shipping_export_plugin.form.type.dhl_shipping_gateway:
        class: BitBag\Dhl24ShippingExportPlugin\Form\Type\DhlShippingGatewayType
        tags:
            - { name: bitbag.shipping_gateway_configuration_type, type: "dhl24", label: "DHL24" }

    bitbag.dhl_shipping_export_plugin.event_listener.dhl_shipping_export:
        class: BitBag\Dhl24ShippingExportPlugin\EventListener\DhlShippingExportEventListener
        tags:
            - { name: kernel.event_listener, event: 'bitbag.export_shipment', method: exportShipment }