parameters:
    bitbag.dhl_wsdl: https://dhl24.com.pl

services:
    bitbag.dhl24_pl_shipping_export_plugin.form.type.dhl_shipping_gateway:
        class: BitBag\SyliusDhl24PlShippingExportPlugin\Form\Type\ShippingGatewayType
        tags:
            - { name: bitbag.shipping_gateway_configuration_type, type: 'dhl24_pl', label: "DHL24 PL" }

    bitbag.dhl24_pl_shipping_export_plugin.api.shipping_label_fetcher:
        class: BitBag\SyliusDhl24PlShippingExportPlugin\Api\ShippingLabelFetcher
        arguments:
            - '@session.flash_bag'
            - '@bitbag.dhl24_pl_shipping_export_plugin.api.web_client'
            - '@bitbag.dhl24_pl_shipping_export_plugin.api.soap_client'

    bitbag.dhl24_pl_shipping_export_plugin.event_listener.dhl_shipping_export:
        class: BitBag\SyliusDhl24PlShippingExportPlugin\EventListener\ShippingExportEventListener
        arguments:
            - '@filesystem'
            - '@bitbag.manager.shipping_export'
            - '%bitbag.shipping_labels_path%'
            - '@bitbag.dhl24_pl_shipping_export_plugin.api.shipping_label_fetcher'
        tags:
            - { name: kernel.event_listener, event: 'bitbag.shipping_export.export_shipment', method: exportShipment }

    bitbag.dhl24_pl_shipping_export_plugin.api.web_client:
        class: BitBag\SyliusDhl24PlShippingExportPlugin\Api\WebClient

    bitbag.dhl24_pl_shipping_export_plugin.api.soap_client:
        class: BitBag\SyliusDhl24PlShippingExportPlugin\Api\SoapClient
